"""Added keyword-datasource table set

Revision ID: b87a389fe98d
Revises: 8ca37b98ee74
Create Date: 2017-07-11 18:37:20.169102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87a389fe98d'
down_revision = '8ca37b98ee74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=256), server_default=sa.text('CURRENT_USER'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('ne_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=256), server_default=sa.text('CURRENT_USER'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nlp_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ne_tag', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=256), server_default=sa.text('CURRENT_USER'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['ne_tag'], ['ne_tag.id'], ),
    sa.UniqueConstraint('url')
    )
    op.create_table('association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasource', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=256), server_default=sa.text('CURRENT_USER'), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['datasource'], ['datasource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=256), server_default=sa.text('CURRENT_USER'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('keyword_association',
    sa.Column('association', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['association'], ['association.id'], ),
    sa.ForeignKeyConstraint(['keyword'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('association', 'keyword')
    )
    op.create_table('keyword_datasource',
    sa.Column('keyword', sa.Integer(), nullable=False),
    sa.Column('datasource', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=256), server_default=sa.text('CURRENT_USER'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['datasource'], ['datasource.id'], ),
    sa.ForeignKeyConstraint(['keyword'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('keyword', 'datasource')
    )
    op.create_table('keyword_ne_tag',
    sa.Column('keyword', sa.Integer(), nullable=False),
    sa.Column('ne_tag', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=256), server_default=sa.text('CURRENT_USER'), nullable=False),
    sa.ForeignKeyConstraint(['ne_tag'], ['ne_tag.id'], ),
    sa.ForeignKeyConstraint(['keyword'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('keyword', 'ne_tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_datasource')
    op.drop_table('keyword_ne_tag')
    op.drop_table('keyword_association')
    op.drop_table('keyword')
    op.drop_table('association')
    op.drop_table('nlp_model')
    op.drop_table('ne_tag')
    op.drop_table('datasource')
    # ### end Alembic commands ###
